name: Deploy CDK Infrastructure Stacks to AWS

on:
  push:
    paths: 
      - packages/cdk-infra/**
      - .github/workflows/cdk-infra-deploy.yml

  workflow_dispatch:

jobs:

  deployInfrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - uses: actions/checkout@v2
      
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Install npm dependencies
        run: npm install
      
      - run: ls
      
      - run:  cd packages && ls
      
      - name: Bootstrap 
        run: npm run bootstrap
        
      - name: Deploy
        run: npm run deploy
        
